#!/bin/bash

CONFIG_PATH={$0}
FILT_NAME="$1.filt"
FILTERS={$2}
STAR_LIB_BINARY_NAME={$3} #"STAR+BD"
QSO_LIB_BINARY_NAME={$4} #"QSO_MARA"
GAL_LIB_BINARY_NAME={$5} #"BC03"

STAR_LIB_NAME=${STAR_LIB_BINARY_NAME}_${FILT_NAME}
QSO_LIB_NAME=${QSO_LIB_BINARY_NAME}_${FILT_NAME}
GAL_LIB_NAME=${GAL_LIB_BINARY_NAME}_${FILT_NAME}

# assume binaries and templates have already been compiled

# make stellar template set
$LEPHAREDIR/source/mag_star -c $CONFIG_PATH -FILTER_LIST $FILTERS -FILTER_FILE $FILT_NAME -STAR_LIB_OUT $STAR_LIB_NAME

# make QSO template set
$LEPHAREDIR/source/mag_gal -t Q -c $CONFIG_PATH -FILTER_LIST $FILTERS -FILTER_FILE $FILT_NAME -QSO_LIB_OUT $QSO_LIB_NAME

# make galaxy template set (takes by far the longest)
$LEPHAREDIR/source/mag_gal -t G -c $CONFIG_PATH -FILTER_LIST $FILTERS -FILTER_FILE $FILT_NAME -GAL_LIB_OUT $GAL_LIB_NAME