#!/bin/bash

OUTPUT_DIR=$1
INPUT_IMAGE_PATH=$2
PIXEL_SCALE=$3
MAG_ZEROPOINT=$4
INSTRUMENT=$5
SURVEY=$6
BAND=$7
VERSION=$8

# make appropriate directories
OUTPUT_CAT_DIR=${OUTPUT_DIR}/SExtractor/${INSTRUMENT}/${VERSION}/${SURVEY}
mkdir -p $OUTPUT_CAT_DIR
OUTPUT_CAT_PATH=${OUTPUT_CAT_DIR}/${SURVEY}_${BAND}_${BAND}_sel_cat_${VERSION}

# run sextractor
sex ${INPUT_IMAGE_PATH}'[1]' -c ${OUTPUT_DIR}/SExtractor/nircam.sex -WEIGHT_TYPE MAP_RMS -PIXEL_SCALE ${PIXEL_SCALE} -WEIGHT_IMAGE ${INPUT_IMAGE_PATH}'[2]' \
        -CATALOG_NAME ${OUTPUT_CAT_PATH}.fits -MAG_ZEROPOINT ${MAG_ZEROPOINT} \
        -CHECKIMAGE_NAME ${OUTPUT_CAT_PATH}_seg.fits,${OUTPUT_CAT_PATH}_bkg.fits \
        -CHECKIMAGE_TYPE SEGMENTATION,-BACKGROUND