#!/bin/bash

OUTPUT_DIR=$1
INPUT_IMAGE_PATH=$2
PIXEL_SCALE=$3
MAG_ZEROPOINT=$4
INSTRUMENT=$5
SURVEY=$6
BAND=$7
VERSION=$8
FORCED_PHOT_BAND=$9
FORCED_PHOT_IMAGE_PATH=${10}
INPUT_WEIGHT_PATH=${11}
INPUT_WEIGHT_EXT=${12}
INPUT_IMAGE_EXT=${13}
FORCED_PHOT_WEIGHT_PATH=${14}
FORCED_PHOT_EXT=${15}
WEIGHT_TYPE=${16} # Weight types have to be the same for both images
FORCED_PHOT_WEIGHT_EXT=${17}
CONFIG_PATH=${18}
PARAMETERS_NAME=${19}
PHOT_APERTURES=${20}

echo $CONFIG_PATH
echo $PARAMETERS_NAME
echo $PHOT_APERTURES

# make appropriate directories
OUTPUT_CAT_DIR=${OUTPUT_DIR}/SExtractor/${INSTRUMENT}/${VERSION}/${SURVEY}
mkdir -p $OUTPUT_CAT_DIR
OUTPUT_CAT_PATH=${OUTPUT_CAT_DIR}/${SURVEY}_${BAND}_${FORCED_PHOT_BAND}_sel_cat_${VERSION}

sex ${FORCED_PHOT_IMAGE_PATH}'['${FORCED_PHOT_EXT}']' ${INPUT_IMAGE_PATH}'['${INPUT_IMAGE_EXT}']' -c ${CONFIG_PATH} -WEIGHT_TYPE ${WEIGHT_TYPE} -PIXEL_SCALE ${PIXEL_SCALE} -WEIGHT_IMAGE ${FORCED_PHOT_WEIGHT_PATH}'['${FORCED_PHOT_WEIGHT_EXT}']',${INPUT_WEIGHT_PATH}'['${INPUT_WEIGHT_EXT}']' \
        -CATALOG_NAME ${OUTPUT_CAT_PATH}.fits -MAG_ZEROPOINT ${MAG_ZEROPOINT} \
        -CHECKIMAGE_TYPE NONE -PARAMETERS_NAME ${PARAMETERS_NAME} -PHOT_APERTURES ${PHOT_APERTURES}