#!/bin/bash


OUTPUT_DIR=$1
INPUT_IMAGE_PATH=$2
PIXEL_SCALE=$3
MAG_ZEROPOINT=$4
INSTRUMENT=$5
SURVEY=$6
BAND=$7
VERSION=$8
INPUT_WEIGHT_PATH=$9
INPUT_WEIGHT_EXT=${10}
INPUT_WEIGHT_TYPE=${11}
INPUT_IMAGE_EXT=${12}
CONFIG_PATH=${13}
PARAMETERS_NAME=${14}
# make appropriate directories
OUTPUT_CAT_DIR=${OUTPUT_DIR}/SExtractor/${INSTRUMENT}/${VERSION}/${SURVEY}
mkdir -p $OUTPUT_CAT_DIR
OUTPUT_CAT_PATH=${OUTPUT_CAT_DIR}/${SURVEY}_${BAND}_${BAND}_sel_cat_${VERSION}
echo $INPUT_IMAGE_EXT   
echo $FORCED_PHOT_EXT
echo $INPUT_WEIGHT_EXT
echo $FORCED_PHOT_WEIGHT_EXT
echo $INSTRUMENT
# run sextractor
sex ${INPUT_IMAGE_PATH}'['${INPUT_IMAGE_EXT}']' -c ${CONFIG_PATH} -WEIGHT_TYPE $INPUT_WEIGHT_TYPE -PIXEL_SCALE ${PIXEL_SCALE} -WEIGHT_IMAGE ${INPUT_WEIGHT_PATH}'['${INPUT_WEIGHT_EXT}']' \
        -CATALOG_NAME ${OUTPUT_CAT_PATH}.fits -MAG_ZEROPOINT ${MAG_ZEROPOINT} \
        -CHECKIMAGE_NAME ${OUTPUT_CAT_PATH}_seg.fits,${OUTPUT_CAT_PATH}_bkg.fits \
        -CHECKIMAGE_TYPE SEGMENTATION,-BACKGROUND \
        -PARAMETERS_NAME ${PARAMETERS_NAME}