#!/bin/bash

LEPHARE_CONFIG_PATH=$1
CAT_IN_PATH=$2
CAT_OUT_PATH=$3
GALFIND_DIR=$4
SED_OUT_PATH=$5

cd $SED_OUT_PATH

$LEPHAREDIR/source/zphota -c $LEPHARE_CONFIG_PATH -CAT_IN $CAT_IN_PATH -CAT_OUT $CAT_OUT_PATH

cd $GALFIND_DIR