#!/bin/bash

LEPHARE_CONFIG_PATH=$1
CAT_IN_PATH=$2
CAT_OUT_PATH=$3
GALFIND_DIR=$4
SED_OUT_PATH=$5
TEMPLATE_LIB_NAME=$6

GAL_TEMPLATE_NAME="BC03_NIRCAM_HST" #"BC03_${TEMPLATE_LIB_NAME}_HZ_Dusty"
STAR_TEMPLATE_NAME="STAR_NIRCAM_HST" #"STAR+BD_${TEMPLATE_LIB_NAME}"
QSO_TEMPLATE_NAME="QSO_NIRCAM_HST" #"QSO_MARA_${TEMPLATE_LIB_NAME}_HZ_Dusty"

cd $SED_OUT_PATH

$LEPHAREDIR/source/zphota -c $LEPHARE_CONFIG_PATH -CAT_IN $CAT_IN_PATH -CAT_OUT $CAT_OUT_PATH -ZPHOTLIB ${GAL_TEMPLATE_NAME},${STAR_TEMPLATE_NAME},${QSO_TEMPLATE_NAME}

cd $GALFIND_DIR
