#!/bin/bash

LEPHARE_CONFIG_PATH=$1
CAT_IN_PATH=$2
CAT_OUT_PATH=$3
GALFIND_DIR=$4
GAL_LIB_NAME=$5
STAR_LIB_NAME=$6
QSO_LIB_NAME=$7
RUN_DIR=$8

cd $RUN_DIR

$LEPHAREDIR/source/zphota -c $LEPHARE_CONFIG_PATH -CAT_IN $CAT_IN_PATH -CAT_OUT $CAT_OUT_PATH -ZPHOTLIB ${GAL_LIB_NAME},${STAR_LIB_NAME},${QSO_LIB_NAME}

cd $GALFIND_DIR
