[DEFAULT]
SURVEY: CLIO
GALFIND_WORK: /raid/scratch/work/austind/GALFIND_WORK
#/Users/user/galfind_env/GALFIND_WORK
#/raid/scratch/work/austind/GALFIND_WORK
GALFIND_DATA: /raid/scratch/data
#/Users/user/galfind_env/data
#/raid/scratch/data
N_CORES: 1
USE_LOGGING: YES
# set logging level (can be NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL)
LOGGING_LEVEL: INFO
#INFO
LOGGING_OUT_DIR: %(GALFIND_WORK)s/Log_files
CONFIG_DIR: %(GALFIND_DIR)s/../configs

[DataReduction]
# Pixel scale in arcsec
NIRCAM_PIXEL_SCALE: 0.03

[PSF]
PSF_DIR: %(CONFIG_DIR)s/psfs
PSF_WORK_DIR: %(GALFIND_WORK)s/PSFs
PSF_PLOT_DIR: %(PSF_WORK_DIR)s/Plots
STPSF_CACHE: %(PSF_WORK_DIR)s/stpsf_cache/stpsf-data

[SExtractor]
SEX_DIR: %(GALFIND_WORK)s/SExtractor
SEX_CONFIG_DIR: %(CONFIG_DIR)s/SExtractor
# Aperture diameters to use in arcsec
APERTURE_DIAMS: [0.32, 0.5, 1.0, 1.5, 2.0]

[Photutils]
PHOTUTILS_DIR: %(GALFIND_WORK)s/Photutils

[Depths]
DEPTH_DIR: %(GALFIND_WORK)s/Depths

[Masking]
MASK_DIR: %(GALFIND_WORK)s/Masks

[Cutouts]
CUTOUT_DIR: %(GALFIND_WORK)s/Cutouts

[RGB]
RGB_DIR: %(GALFIND_WORK)s/RGBs

[EAZY]
EAZY_DIR: %(GALFIND_WORK)s/EAZY
EAZY_TEMPLATE_DIR: %(GALFIND_DIR)s/../configs/EAZY_templates/templates
EAZY_CONFIG_DIR: %(CONFIG_DIR)s
#/EAZY
Z_MIN: 0
Z_MAX: 25
Z_STEP: 0.01
N_PROC: 0
# by default this avoids multi-processing
SAVE_UBVJ: YES

[LePhare]
LEPHARE_DIR: %(GALFIND_WORK)s/LePhare
LEPHARE_CONFIG_DIR: %(CONFIG_DIR)s/LePhare
LEPHARE_CONFIG_FILE: $(LEPHARE_CONFIG_DIR)s/default.para
LEPHARE_SED_DIR: %(LEPHARE_CONFIG_DIR)s/sed
STAR_TEMPLATES: STAR_BD_DEFAULT
QSO_TEMPLATES: QSO_DEFAULT
GAL_AGES: %(LEPHARE_SED_DIR)s/GAL/BC03_AGE
COMPILE_SURVEY_FILTERS: YES
Z_STEP: 0.04,18.0,0.1
COSMOLOGY: 70,0.3,0.7
MOD_EXTINC: 0,129
EXTINC_LAW: calzetti.dat
EB_V: 0.0,0.05,0.1,0.15,0.2,0.3,0.6,1.0,1.5,2.0,2.5,3.0
EM_LINES: YES

[Bagpipes]
PIPES_DIR: /nvme/scratch/work/austind/Bagpipes/pipes
PIPES_FILT_DIR: %(PIPES_DIR)s/filters
PIPES_OUT_DIR: %(GALFIND_WORK)s/Bagpipes

[TemplateFitting]
BROWN_DWARF_OUT_DIR: %(GALFIND_WORK)s/Brown_Dwarfs

[GALFIT]
GALFIT_INSTALL_PATH: /nvme/scratch/software/galfit3
GALFIT_DIR: %(GALFIND_WORK)s/GALFIT
INPUT_DIR: %(GALFIT_DIR)s/input
OUTPUT_DIR: %(GALFIT_DIR)s/output
GALFIT_PLOT_DIR: %(GALFIT_DIR)s/plots

[PYSERSIC]
PYSERSIC_DIR: %(GALFIND_WORK)s/PySersic
OUTPUT_DIR: %(PYSERSIC_DIR)s/output

[PhotProperties]
PDF_SAVE_DIR: %(GALFIND_WORK)s/RestPhot_PDFs

[MockSEDs]
IGM_PRESCRIPTION: Inoue+14
IGM_DIR: %(GALFIND_DIR)s/IGM_attenuation

[Spectra]
DJA_WEB_DIR: https://s3.amazonaws.com/msaexp-nirspec/extractions
DJA_CAT_PATH: %(GALFIND_DIR)s/../configs/DJA_spectral_catalogues/DJA_v4_4.csv
DJA_1D_SPECTRA_DIR: %(GALFIND_WORK)s/Spectra/1D
DJA_2D_SPECTRA_DIR: %(GALFIND_WORK)s/Spectra/2D
R_CURVE_DIR: %(CONFIG_DIR)s/JWST_R_curves

[NumberDensityFunctions]
NUMBER_DENSITY_FUNC_DIR: %(GALFIND_WORK)s/Number_Density_Functions
VMAX_DIR: %(NUMBER_DENSITY_FUNC_DIR)s/Vmax
FLAGS_DATA_DIR: /nvme/scratch/work/austind/flags_data

[Other]
CLUSTER_FIELDS: ["El-Gordo", "MACS-0416", "CLIO", "SMACS-0723"]
# Organised instrument names blue -> red
INSTRUMENT_NAMES: ["MegaCam", "HSC", "VISTA", "VIS", "ACS_SBC", "ACS_WFC", "WFC3_IR", "NISP", "NIRCam", "IRAC", "MIRI"]
FACILITY_NAMES: ["CFHT", "Subaru", "Paranal", "HST", "Euclid", "JWST", "Spitzer"]
PLOT_DIR: %(GALFIND_WORK)s/Plots
